#
# Copyright (c) 2019-2020, Lawrence Livermore National Security, LLC and
# other Serac Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)
#

variables:
  DO_BUILD: 'yes'
  DO_TEST: 'yes'
  DO_CLEAN: 'no'

strategy:
  matrix:
   linux_gcc8:
      VM_ImageName: 'ubuntu-16.04'
      Compiler_ImageName: 'seracllnl/tpls:gcc-8'
      CMAKE_EXTRA_FLAGS: ''
      COMPILER: 'g++'
      TEST_TARGET: 'linux_gcc8'
      HOST_CONFIG: 'docker-linux-ubuntu16.04-x86_64-gcc@8.1.0'

pool:
  vmImage: $(VM_ImageName)

steps:
- checkout: self
  clean: true
  submodules: recursive
- script:  |
    echo " -e $TEST_TARGET -e $COMPILER -e $DO_BUILD -e $DO_TEST -e $CMAKE_EXTRA_FLAGS $(Compiler_ImageName) ./scripts/azure-pipelines/linux-build_and_test.sh"
    docker run --rm --user='root' -v `pwd`:/home/serac/serac $(Compiler_ImageName) chown -R serac /home/serac
    docker run --rm -v `pwd`:/home/serac/serac -e TEST_TARGET -e COMPILER -e DO_BUILD -e DO_TEST -e DO_CLEAN -e HOST_CONFIG -e CMAKE_EXTRA_FLAGS $(Compiler_ImageName) ./serac/scripts/azure-pipelines/linux-build_and_test.sh

  displayName: '$(TEST_TARGET) Build & Test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'cTest'
    testResultsFiles: '**/Test.xml'
    testRunTitle: '$(TEST_TARGET) Tests'
    failTaskOnFailedTests: true
